trigger: 
   branches:
      include:
          - none
      exclude:
          - none 
pr:
    branches:
     include:
         - none
     exclude:
         - none 
      
schedules:
    - cron: "0 17 * * 2,5"
      displayName: 
      branches:
       include:
           - develop

stages:
    - stage: Test
      displayName: Test Stage
      jobs:
        - job: runAutomationTest
          timeoutInMinutes: 600
          displayName: RunAutomationTest
          pool: 
           vmImage: 'windows-latest'
          steps:
            # - script: echo "Running tests..."
            - task: JavaToolInstaller@1
              inputs:
                versionSpec: '8'
                jdkArchitectureOption: 'x64'
                jdkSourceOption: 'PreInstalled'
            - task: replacetokens@6
              inputs:
                root: 'src/test/resources'
                sources: 'data.properties'
            
            - task: MavenAuthenticate@0
              inputs:
                artifactsFeeds: 'Java-jar'
            
            - task: DownloadSecureFile@1
              inputs:
                secureFile: 'settings.xml'

            - script: |
                mkdir -p ~/.m2
                cp "$(Agent.TempDirectory)/settings.xml" ~/.m2/settings.xml
                echo "Custom settings.xml copied to ~/.m2"
              displayName: 'Configure Maven settings.xml'

            # Now run Maven deploy (no need to specify --settings, Maven will pick ~/.m2/settings.xml)
            - script: |
                mvn deploy
              displayName: 'Maven Deploy'
    

            - task: Maven@4
              inputs:
                mavenPomFile: 'pom.xml'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                javaHomeOption: 'JDKVersion'
                mavenVersionOption: 'Default'
                mavenAuthenticateFeed: false
                effectivePomSkip: false
                sonarQubeRunAnalysis: false     
            - task: CopyFiles@2
              inputs:
                SourceFolder: '$(Build.SourcesDirectory)'
                Contents: '**'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'
            - task: NodeTool@0
              inputs:
                versionSource: 'spec'
                versionSpec: '18.x'
                checkLatest: true
            - task: PublishCucumberReport@1
              inputs:
                jsonDir: '$(Build.ArtifactStagingDirectory)'
                outputPath: '$(System.DefaultWorkingDirectory)'
                theme: 'bootstrap'
                reportSuiteAsScenarios: true
             


